#!/bin/bash -e

rm -rf classes *.jar

lein deps
lein do uberjar, difftest, run -m marginalia.main --file index.html

echo "(exit)" | ./shen.clj
echo

yes | lein trampoline run -m shen.test 2>&1 | tee test.log
grep -q "failed; continue? (y/n)" test.log && exit 1
