#!/bin/bash -e

rm -rf classes *.jar lib

lein deps
lein uberjar, difftest, run -m marginalia.main --file index.html

echo "(exit)" | java -jar shen.clj-*-standalone.jar
echo

yes | lein trampoline run -m shen.test 2>&1 | tee test.log
grep "pass rate ...100.0%" test.log > /dev/null
