#!/bin/bash -e

rm -rf classes *.jar

lein deps
lein uberjar, difftest, run -m marginalia.main --file index.html

echo "(exit)" | ./shen.clj
echo

yes | lein trampoline run -m shen.test 2>&1 | tee test.log
grep "pass rate ...100%" test.log > /dev/null
