#!/bin/bash -e

version=$(cat project.clj | head -n 1 | awk '{print $3}' | sed s/\"//g)
target=shen.clj-$version

echo "copying into $target"
rm -rf "$target"
mkdir -p "$target"
cp -a src project.clj README shen.clj shen-clj.bat shen.clj-*-standalone.jar "$target"

git rev-parse --short HEAD > "$target"/version.txt

rm -f $target.zip
zip -qr $target.zip $target
